In [225]:
import numpy as np

In [226]:
#input data
input_data=np.array([[0,0,0],
                     [0,1,1],
                     [1,1,0],
                     [1,1,1],
                     [0,0,1],
                     [0,1,0],
                     [1,0,0]])

output_labels = np.array([[0],
                          [0],
                          [0],
                          [1],
                         [1],
                         [1],
                         [1]])

print(input_data, output_labels)

[[0 0 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]] [[0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


In [227]:
def activate(x):
    return 1/(1+np.exp(-x))

In [228]:
def transfer_derivative(output):
    return output *(1-output)

In [238]:
np.random.seed(1)
w0=np.random.random((3,5))-1
w1=np.random.random((5,1))-1

In [239]:
def feed_forward(input_data):
    layer0=input_data
    layer1= activate(np.dot(layer0,w0))
    layer2= activate(np.dot(layer1,w1))
    
    return layer0,layer1,layer2

In [240]:
def backpropogate(j, layer0,layer1,layer2,w1,w0,learning_rate):
    l2_error=layer2-output_labels
    
    if(j%1000==0):
        print("Error:"+str(np.mean(np.abs(l2_error))))
    
    l2_delta=l2_error*transfer_derivative(layer2)
    dl2=layer1.T.dot(l2_delta)
    
    l1_error=l2_delta.dot(w1.T)
    l1_delta= l1_error*transfer_derivative(layer1)
    dl1=layer0.T.dot(l1_delta)
    
    w1 -= dl2*learning_rate
    w0 -= dl1*learning_rate
    
    return w1,w0

In [250]:
for i in range(30000):
    layer0 ,layer1 ,layer2 = feed_forward(input_data)
    w1,w0= backpropogate(i,layer0,layer1,layer2,w1,w0,0.05)

Error:0.0359680507141046
Error:0.03510145338305724
Error:0.03429202043687702
Error:0.03353382037134841
Error:0.032821742441892
Error:0.03215135690076036
Error:0.03151880316418963
Error:0.03092069956098087
Error:0.03035406991950818
Error:0.02981628341123917
Error:0.029305004918503113
Error:0.028818153822827604
Error:0.028353869579979707
Error:0.02791048280237419
Error:0.027486490839422378
Error:0.027080537053640347
Error:0.026691393150699443
Error:0.026317944046643022
Error:0.025959174853650218
Error:0.025614159643314323
Error:0.025282051708106816
Error:0.024962075091063074
Error:0.024653517193446
Error:0.024355722302273248
Error:0.024068085905718954
Error:0.023790049685743938
Error:0.02352109709482863
Error:0.023260749438128826
Error:0.023008562394334204
Error:0.022764122918454893


In [251]:
layer0 ,layer1, layer2= feed_forward([1,1,1])

In [252]:
print(layer2)

[0.99399122]


In [253]:
w0


array([[-0.18695717,  4.20051045, -3.1728951 , -3.76583456,  6.42629549],
       [ 1.35024808, -8.06097923, -4.95012172, -3.61513109, -3.63237613],
       [-0.39051507,  4.18334426, -3.03159967,  6.40180397, -3.91440097]])

In [254]:
w1

array([[ 4.70061322],
       [10.30625326],
       [-6.40490805],
       [-7.77347922],
       [-7.98001922]])